# STAA57 Project Proposal
`Avoid deleting other people's work when possible (anything in backticks is not intended to be final and can be deleted)`

### Analysis Plan
`Specify questions to be adressed`
With the data given and additional data on weather and seasons, the following questions will be adressed by our analysis: `Ideally we'll end up with 3 questions so  some may be      cut or combined to give more concrete analysis`

  - Are longer sessions more beneficial to student performance? `This may/may not be concrete enough to make the final draft depending on what further analysis concludes`
  - Which season(s) see the best average student performance?
  - Instructor/student data relationship (Do some students fare better with certain instructors?) `The wording of this is unclear. Feel free to delete and reword this if you have    a better description`
  - What is the ideal time between training sessions to maximise student performance?
  - How can students succeed the quickest?  `Success can be defined as flying solo, flying cross country, completing all exercises at least once?`

`Describe data analysis plan`

### Data
`List/specify external data sources and types of data`
`R Code for importing data will not go  in this section (since it is 100+ lines, ideally it goes in the appendix)`

### Preliminary Analysis
`Put in >= 3 graphs/DaVis' relating to analysis and comment on preliminary findings.`

Comparing the general trend of the number of exercises completed in each session to the duration of the sessions shows that a longer session duration does not guarantee more exercises will be completed. The correlations is also very weak implying that there is a significant difference between the length of exercises and/or that there are too many extra factors that cannot be accounted for such as adverse conditions or unexpected issues with the airplane.

Upon comparing the average length of sessions where only one exercise was completed, this implication was confirmed. The length of single exercise sessions, even when comparing sessiosn where the same one exercise was completed, varied widely on some exercises. In addition, most single exercises either had no sessions or very few sessions to compare.

### Appendix
`R Code for cleaning and importing data goes here (I am rewriting my code to be more space efficient. If I can compress it enough, I might be able to move it into the data section`
